const morseItems = [
  {letter:'a', morse:'._'},
  {letter:'b', morse:'_...'},
  {letter:'c', morse:'_._.'},
  {letter:'d', morse:'_..'},
  {letter:'e', morse:'.',},
  {letter:'f', morse:'.._.'},
  {letter:'g', morse:'__.'},
  {letter:'h', morse:'....',},
  {letter:'i', morse:'..'},
  {letter:'j', morse:'.___'},
  {letter:'k', morse:'_._'},
  {letter:'l', morse:'._..'},
  {letter:'m', morse:'__'},
  {letter:'n', morse:'_.'},
  {letter:'o', morse:'___'},
  {letter:'p', morse:'.__.'},
  {letter:'q', morse:'__._'},
  {letter:'r', morse:'._.'},
  {letter:'s', morse:'...',},
  {letter:'t', morse:'_'},
  {letter:'u', morse:'.._'},
  {letter:'v', morse:'..._'},
  {letter:'w', morse:'.__'},
  {letter:'x', morse:'_.._'},
  {letter:'y', morse:'_.__'},
  {letter:'z', morse:'__..'},
  {letter:'1', morse:'.____'},
  {letter:'2', morse:'..___'},
  {letter:'3', morse:'...__'},
  {letter:'4', morse:'...._'},
  {letter:'5', morse:'.....',},
  {letter:'6', morse:'_....'},
  {letter:'7', morse:'__...'},
  {letter:'8', morse:'___..'},
  {letter:'9', morse:'____.'},
  {letter:'0', morse:'_____'},
]

export default morseItems